serverAddr = "106.54.188.236"
serverPort = 7000
auth.method = "token"
auth.token = "Story2Video"

[[visitors]]
name = "server-8080-visitor"
type = "stcp"
serverName = "server-8080-stcp"  # 必须与 frpc.toml 中的 name 一致
secretKey = "story-secret"
bindAddr = "127.0.0.1"
bindPort = 18080  # 客户端本地监听端口
